modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/NaturesauraTweaker/issues"

[[mods]]
modId="naturesaura_tweaker"
version="0.0.1"
displayName="Natures Aura Tweaker"
displayURL="https://www.curseforge.com/minecraft/mc-mods/naturesaura_tweaker"
authors="Mrthomas20121"
description='''
Add Crafttweaker support to Natures Aura
'''

[[dependencies.naturesaura_tweaker]]
	modId = "crafttweaker"
    mandatory = true
    versionRange = "[9.0.57,)"
    ordering = "NONE"
    side = "BOTH"